In [18]:
import torch

x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

#Addition
z1 = torch.empty(3)
torch.add(x, y, out=z1)
print(z1)

z = x - y

z = torch.true_divide(x, y)

#t.add_(x)

#exponentiation
z = x.pow(2)
z = x ** 2

# simple comparison
z = x > 0
z = x < 0

# Matrix multiplication
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))

x3 = torch.mm(x1, x2)
print(x3)

# matrix exponentiation
matrix_exp = torch.rand(5, 5)
print(matrix_exp.matrix_power(3))


# element wise mult
z = x * y
print(z)

#dot product
z = torch.dot(x, y)
print(z)

#batch matrix multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))

out_bmm = torch.bmm(tensor1, tensor2)
print(out_bmm.shape)

# example of broadcasting
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))

z = x1 - x2

# other userful tensor operation
sum_x = torch.sum(x, dim=0)

values, indices = torch.max(x, dim=0) # x.max(dim=0)
values, indices = torch.min(x, dim=0)

z = torch.argmax(x, dim=0) #只返回索引
z = torch.argmin(x, dim=0)

mean_x = torch.mean(x.float(), dim=0)

z = torch.eq(x, y)
print(z)

sorted_y, indices = torch.sort(y, dim=0, descending=False)
print(sorted_y)

z = torch.clamp(x, min=0, max=10)

x = torch.tensor([1, 0, 1,1, 1], dtype=torch.bool)
print(torch.any(x))
print(torch.all(x))


tensor([10., 10., 10.])
tensor([[0.9339, 1.1032, 0.8480],
        [0.7650, 0.7677, 0.3517]])
tensor([[4.1526, 2.9296, 3.6121, 3.8225, 4.2885],
        [4.0871, 2.8967, 3.4796, 4.0233, 4.4718],
        [4.7377, 3.2600, 4.0801, 4.4466, 4.9889],
        [6.7500, 4.6584, 5.8384, 6.3942, 7.0054],
        [2.8127, 1.8885, 2.3964, 2.6036, 3.0182]])
tensor([ 9, 16, 21])
tensor(46)
torch.Size([32, 10, 30])
tensor([False, False, False])
tensor([7, 8, 9])
tensor(True)
tensor(False)


In [ ]:
torch.manual_seed(1) #设置随机数的种子，设置之后，每次生成的随机数会是固定的
indices = torch.randperm(10)
print(indices)

In [31]:
# tensor indexing
import torch

batch_size = 10
features = 25

x = torch.rand((batch_size, features))

print(x[0]) #get first example
print(x[0].shape)

print(x[0, :]) # get first example
print(x[0, :].shape)


print(x[:, 0]) # get first feature of all examples
print(x[:, 0].shape)

#get the first ten features of the third examples
print(x[2, 0:10])


# fancy indexing
x = torch.arange(10)
indices = [2, 5, 8]

print(x[indices])

x = torch.rand((3, 5))
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])

print(x[rows, cols]) # pick out x(1, 4) and x(0, 0)

#more advanced indexing
x = torch.arange(10)

print(x[(x < 2) | (x > 8)])

print(x[x.remainder(2) == 0]) # pick out all the even elements

#useful operations
print(torch.where(x > 5, x, x*2)) # if x > 5 ,set x to x, else set x to x*2
print(torch.tensor([0,0,1,2,2,3,4]).unique())

print(x.ndimension())
print(x.numel()) # count the elements in tensor


tensor([0.0442, 0.3514, 0.1823, 0.9834, 0.1302, 0.6832, 0.6170, 0.0013, 0.8368,
        0.6897, 0.3156, 0.2910, 0.4588, 0.0102, 0.7986, 0.6714, 0.1610, 0.7939,
        0.2004, 0.5710, 0.2951, 0.1436, 0.1445, 0.1292, 0.1962])
torch.Size([25])
tensor([0.0442, 0.3514, 0.1823, 0.9834, 0.1302, 0.6832, 0.6170, 0.0013, 0.8368,
        0.6897, 0.3156, 0.2910, 0.4588, 0.0102, 0.7986, 0.6714, 0.1610, 0.7939,
        0.2004, 0.5710, 0.2951, 0.1436, 0.1445, 0.1292, 0.1962])
torch.Size([25])
tensor([0.0442, 0.4319, 0.8136, 0.2769, 0.1902, 0.5702, 0.6922, 0.2409, 0.2115,
        0.0828])
torch.Size([10])
tensor([0.8136, 0.9378, 0.9954, 0.0085, 0.0091, 0.9973, 0.0156, 0.9176, 0.2757,
        0.5843])
tensor([2, 5, 8])
tensor([0.7010, 0.8044])
tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])
tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10


In [47]:
#tensor reshaping
x = torch.arange(9)

x_3_3 = x.view(3,3) #continuous memory
print(x_3_3.shape)
print(x_3_3)

x_3_3_reshape = x.reshape(3, 3)
print(x_3_3_reshape.shape)

y = x_3_3.t() #tensor transpose
print(y)

print(y.contiguous().view(9))
#print(y.view(9)) #RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))

print(torch.cat((x1, x2), dim=0).shape)

print(torch.cat((x1, x2), dim=1).shape)

z = x1.view(-1) #flattern x1
print(z.shape)

batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
print(z.shape)

#switch axis
z = x.permute(0,2, 1)
print(z.shape)

#unsqueeze
x = torch.arange(10)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

x = torch.arange(10).unsqueeze(0).unsqueeze(1)
print(x.shape)

z = x.squeeze(1)
print(z.shape)

torch.Size([3, 3])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
torch.Size([3, 3])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
torch.Size([4, 5])
torch.Size([2, 10])
torch.Size([10])
torch.Size([64, 10])
torch.Size([64, 5, 2])
torch.Size([1, 10])
torch.Size([10, 1])
torch.Size([1, 1, 10])
torch.Size([1, 10])


参考自：https://www.youtube.com/watch?v=x9JiIFvlUw