In [3]:
import torch
import torch.nn as nn

emb = nn.Embedding(10, 3)
print(emb)
list(emb.parameters())

Embedding(10, 3)


[Parameter containing:
 tensor([[ 1.5984,  0.2825, -0.8304],
         [ 1.0124,  0.0339, -1.2716],
         [-0.9802,  0.9570, -2.1989],
         [ 1.2425,  1.1049,  1.3478],
         [-1.0611, -0.0910,  0.9003],
         [ 1.3653,  1.0712, -0.8761],
         [-0.4109, -1.8273, -0.9426],
         [-1.4062, -1.1364,  0.0117],
         [ 0.5805, -0.8303, -1.5217],
         [ 0.9895,  1.3804,  0.0556]], requires_grad=True)]

In [4]:
labels = torch.LongTensor([1, 2, 3, 4])
emb(labels)

tensor([[ 1.0124,  0.0339, -1.2716],
        [-0.9802,  0.9570, -2.1989],
        [ 1.2425,  1.1049,  1.3478],
        [-1.0611, -0.0910,  0.9003]], grad_fn=<EmbeddingBackward>)

In [10]:
weight = torch.FloatTensor([[1., 2., 3., 5.], [6., 7., 8., 9.]])
print(weight.shape)

emb_pretrained = nn.Embedding.from_pretrained(weight)
print(list(emb_pretrained.parameters()))

emb_pretrained(torch.LongTensor([1]))

torch.Size([2, 4])
[Parameter containing:
tensor([[1., 2., 3., 5.],
        [6., 7., 8., 9.]])]


tensor([[6., 7., 8., 9.]])

与one hot的比较

In [11]:
sentence = "the quick brown fox jumped over the lazy dog"
words = sentence.split(' ')
print(words)

['the', 'quick', 'brown', 'fox', 'jumped', 'over', 'the', 'lazy', 'dog']


In [13]:
print(set(words))
vocal1 = list(set(words))
print(vocal1)
print(len(vocal1))

{'brown', 'over', 'fox', 'dog', 'the', 'jumped', 'lazy', 'quick'}
['brown', 'over', 'fox', 'dog', 'the', 'jumped', 'lazy', 'quick']
8


one hot encoding

In [15]:
#convert words to indexes
word_to_ix1 = {word: i for i, word in enumerate(vocal1)}
print(word_to_ix1)

{'brown': 0, 'over': 1, 'fox': 2, 'dog': 3, 'the': 4, 'jumped': 5, 'lazy': 6, 'quick': 7}


In [18]:
import torch
from torch.nn.functional import one_hot

words = torch.tensor([word_to_ix1[w] for w in vocal1], dtype=torch.long)
one_hot_encoding = one_hot(words)
print(vocal1)
print(one_hot_encoding)

['brown', 'over', 'fox', 'dog', 'the', 'jumped', 'lazy', 'quick']
tensor([[1, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1]])
