Applies the Softmax function to an n-dimensional input Tensor rescaling them so that the elements of the n-dimensional output Tensor lie in the range [0,1] and sum to 1.


Returns:

    a Tensor of the same dimension and shape as the input with  
    values in the range [0, 1] 
输出tensor的shape与输入tensor的shape是一样的
Arguments:

    dim (int): A dimension along which Softmax will be computed (so every slice  
        along dim will sum to 1).  

In [9]:
import torch.nn as nn
import torch

input_t = torch.randn(2, 3)

m_default = nn.Softmax() #默认情况，等价于dim=1,对一行进行归一化
output_default = m_default(input_t)
print(output_default)

m = nn.Softmax(dim=1) #对一行进行归一化
output = m(input_t)
print(output)

m_dim_0 = nn.Softmax(dim=0) # 对一列进行归一化
output_dim_0 = m_dim_0(input_t)
print(output_dim_0)

m_dim_minus_1 = nn.Softmax(dim=-1)#按照最后一维计算,这里是对一行进行soft归一化
output_dim_minus_1 = m_dim_minus_1(input_t)
print(output_dim_minus_1)


tensor([[0.1421, 0.7977, 0.0602],
        [0.0889, 0.2261, 0.6849]])
tensor([[0.1421, 0.7977, 0.0602],
        [0.0889, 0.2261, 0.6849]])
tensor([[0.5876, 0.7587, 0.0726],
        [0.4124, 0.2413, 0.9274]])
tensor([[0.1421, 0.7977, 0.0602],
        [0.0889, 0.2261, 0.6849]])


<ipython-input-9-f9056add13c2>:7: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  output_default = m_default(input_t)
