# numpy 中的维度交换

- numpy.swapaxes: Interchange two axes of an array.可以用来交换array中任意两个维度，如果要同时交换多个维度则不可以使用这个函数
- https://blog.csdn.net/zqislinux/article/details/100567022

In [4]:
import numpy as np

x = np.array([[1, 2, 3]])
print(x.shape)
print(x)

x_new = np.swapaxes(x, 0, 1)
print(x_new.shape)
print(x_new)

(1, 3)
[[1 2 3]]
(3, 1)
[[1]
 [2]
 [3]]


- numpy数组的行列交换
- https://blog.csdn.net/weixin_39590453/article/details/111678157

In [8]:
import numpy as np

a = np.array([[1,2,3],[2,3,4],[1,6,5],[9,3,4]])

print(a)
print(a.shape)

#交换0，1两列
a[:, [1, 0]] = a[:, [0, 1]]
print(a)

#交换1， 2两行
a[[2,1], :] = a[[1,2], :]
print(a)

[[1 2 3]
 [2 3 4]
 [1 6 5]
 [9 3 4]]
(4, 3)
[[2 1 3]
 [3 2 4]
 [6 1 5]
 [3 9 4]]
[[2 1 3]
 [6 1 5]
 [3 2 4]
 [3 9 4]]


# pytorch中的维度交换

- 使用permute函数
- permute改变...的次序，重新排列
- https://blog.csdn.net/BigData_Mining/article/details/105023780

In [2]:
import torch

a = torch.rand(4, 3, 28, 32)
print(a.shape)
a_permuted = a.permute(0, 2, 3, 1)
print(a_permuted.shape)


torch.Size([4, 3, 28, 32])
torch.Size([4, 28, 32, 3])


- 使用transpose有个限制是只能交换其中两个维度
- https://blog.csdn.net/bagba/article/details/107078172

In [3]:
t = torch.arange(24).reshape(2, 3, 4)
print(t.shape)
print(t)
t_trans_0_2 = t.transpose(0, 2)
print(t_trans_0_2.shape)
print(t_trans_0_2)
t_trans_1_2 = t.transpose(1, 2)
print(t_trans_1_2.shape)
print(t_trans_1_2)

torch.Size([2, 3, 4])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([4, 3, 2])
tensor([[[ 0, 12],
         [ 4, 16],
         [ 8, 20]],

        [[ 1, 13],
         [ 5, 17],
         [ 9, 21]],

        [[ 2, 14],
         [ 6, 18],
         [10, 22]],

        [[ 3, 15],
         [ 7, 19],
         [11, 23]]])
torch.Size([2, 4, 3])
tensor([[[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]],

        [[12, 16, 20],
         [13, 17, 21],
         [14, 18, 22],
         [15, 19, 23]]])
