It is important to note that basic integer-based indexing and slicing create so-called views of NumPy arrays in memory. Working with views can be highly desirable since it avoids making unnecessary copies of arrays to save memory resources.

In [2]:
import numpy as np

ary = np.array([[1, 2, 3],
               [4, 5, 6]])

first_row = ary[0]
first_row += 99
ary #可以看到ary的值发生了改变
#As we can see in the example above, changing the value of first_row also affected the original array. 
# The reason for this is that ary[0] created a view of the first row in ary, and its elements were then incremented by 99

array([[100, 101, 102],
       [  4,   5,   6]])

If we are working with NumPy arrays, it is always important to be aware that slicing creates views -- sometimes it is desirable since it can speed up our code by avoiding to create unnecessary copies in memory. However, in certain scenarios we want force a copy of an array; we can do this via the copy method as shown below:
numpy 的切片创建了view。但是在特定的情境下，我们需要一个copy，而不是view。我们改变copy不会改变原始数组

In [3]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])

second_row = ary[1].copy()
second_row += 99
display(second_row)
ary #可以看到ruan

array([103, 104, 105])

array([[1, 2, 3],
       [4, 5, 6]])

fancy indexing return a copy not a view

In addition to basic single-integer indexing and slicing operations, NumPy supports advanced indexing routines called fancy indexing. Via fancy indexing, we can use tuple or list objects of non-contiguous integer indices to return desired array elements. Since fancy indexing can be performed with non-contiguous sequences, it cannot return a view -- a contiguous slice from memory. Thus, fancy indexing always returns a copy of an array -- it is important to keep that in mind. 

In [4]:
lst = np.array([1, 2, 3, 4, 5])
lst[[0, 2]]

array([1, 3])

In [7]:
ary = np.array([[1, 2, 3],
               [4, 5, 6]])

ary[:, [0, 2]] #first and last column

this_is_a_copy = ary[:, [0, 2]]
this_is_a_copy += 99
print(ary)
print(this_is_a_copy)

[[1 2 3]
 [4 5 6]]
[[100 102]
 [103 105]]


In [8]:
cp = ary[:, [2, 0]] #shuffle the order of the colums,取出第二列和第0列，并且将第2列放在前面，第0列放在后面
cp += 99
cp

array([[102, 100],
       [105, 103]])

Boolean masks 是另一种形式的fancy indexing方式。所以返回的值也是copy。
Note that indexing using Boolean arrays is also considered "fancy indexing" and thus returns a copy of the array.

Finally, we can also use Boolean masks for indexing -- that is, arrays of True and False values. 
Consider the following example, where we return all values in the array that are greater than 3:

In [10]:
ary = np.array([[1,2,3],
               [4, 5, 6]])

greater3_mask = ary > 3
display(greater3_mask)

display(ary[greater3_mask]) # using these masks, we can select elements given our desired criteria:

array([[False, False, False],
       [ True,  True,  True]])

array([4, 5, 6])

我们可以将不同的选择标准通过逻辑运算符 & 或者 | 连接起来。从而进行多个标准的fancy indexing
We can also chain different selection criteria using the logical and operator '&' or the logical or operator '|'. The example below demonstrates how we can select array elements that are greater than 3 and divisible by 2:

In [11]:
ary[(ary>3) & (ary % 2 == 0)]

array([4, 6])

In [12]:
(ary>3) & (ary % 2 == 0)

array([[False, False, False],
       [ True, False,  True]])