## numpy.delete

- Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by arr[obj].

- numpy.delete(arr, obj, axis=None)[source]

- obj : slice, int or array of ints

Indicate which sub-arrays to remove.

- The axis along which to delete the subarray defined by obj. If axis is None, obj is applied to the flattened array.

- out : ndarray

A copy of arr with the elements specified by obj removed. Note that delete does not occur in-place. If axis is None, out is a flattened array.

https://www.cnblogs.com/andrew-address/p/12783695.html

一、函数

np.delete(array,obj,axis)

二、函数的意思

array:需要处理的矩阵

obj:需要处理的位置，比如要删除的第一行或者第一行和第二行

axis:

如果输入为None：array会先按行展开，然后按照obj，删除第obj-1(从0开始)位置的数，返回一个行矩阵。

如果输入为0：按行删除

如果输入为1：按列删除

In [5]:
import numpy as np


arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)

print(np.delete(arr, 1, 0)) #将第2个sub array删除，沿着axis=0，也就是将第一维删除

sub_array = np.delete(arr, [1,3,5], None) #将第1，3，5个元素删除
print(sub_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[ 1  3  5  7  8  9 10 11 12]


## axis输入为None

In [7]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])

#axis输入为None
a_1 = np.delete(a,2,None) #按行展开后，删除第2 +1个数，因为是从0开始的
print(a_1)

[1 2 4 5 6]


## axis输入为0
- 删除一行

In [8]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
a_1 = np.delete(a,0,0)  #删除第一行
print(a_1)

[[3 4]
 [5 6]]


- 删除多行

In [9]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
a_1 = np.delete(a,[0,1],0)
print(a_1)

[[5 6]]


## axis输入为1

- 删除1列

In [10]:
import numpy as np
a = np.array([[1,2,7],[3,4,8],[5,6,9]])
a_1 = np.delete(a,0,1) #删除第一列
print(a_1)

[[2 7]
 [4 8]
 [6 9]]


- 删除多列

In [12]:
import numpy as np
a = np.array([[1,2,7],[3,4,8],[5,6,9]])
a_1 = np.delete(a,[0,2],1) #删除第0列和第2列
print(a_1)

[[2]
 [4]
 [6]]
