# indexing ，slicing与 fancy indexing

- 首先indexing slicing产生原来array的view，而fancy indexing产生的是copy
- In addition to basic single-integer indexing and slicing operations, NumPy supports advanced indexing routines called fancy indexing. Via fancy indexing, we can use tuple or list objects of non-contiguous integer indices to return desired array elements. Since fancy indexing can be performed with non-contiguous sequences, it cannot return a view -- a contiguous slice from memory. Thus, fancy indexing always returns a copy of an array -- it is important to keep that in mind. 


In [1]:
import numpy as np

## fancy indexing
- 不连续的从原来的array中复制出来一些元素

In [13]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])

print(ary[:, [0, 2]]) # first and and last column

this_is_a_copy = ary[:, [0, 2]]
this_is_a_copy += 99
print(ary)

ary[:, [2, 0]] # first and and last column,

print('rearrange colums:\n',ary[:, [2, 0, 1]]) #通过facny indexing 调整了列的顺序

ary = np.array([[1, 2, 3],
                [4, 5, 6]])

greater3_mask = ary > 3
print(greater3_mask)

print(ary[greater3_mask])


[[1 3]
 [4 6]]
[[1 2 3]
 [4 5 6]]
rearrange colums:
 [[3 1 2]
 [6 4 5]]
[[False False False]
 [ True  True  True]]
[4 5 6]


In [11]:
lst = [1, 2, 3, 4, 5]

#print(lst[[0, 2, 4]]) #python list 不支持fancy indexing, TypeError: list indices must be integers or slices, not list

lst_numpy = np.array([1, 2, 3, 4, 5])
print(lst_numpy[[0, 2, 4]])

[1 3 5]


## array indexing
- Simple NumPy indexing and slicing works similar to Python lists

In [6]:
ary = np.array([1, 2, 3])
print(ary[0]) #e retrieve the first element of a one-dimensional array

print(ary[:2]) # equivalent to ary[0:2] # how to fetch the first two elements in ary

ary = np.array([[1, 2, 3],
                [4, 5, 6]])

print(ary[0, 0]) # upper left

print(ary[0]) # entire first row

print(ary[:, 0]) # entire first column

print(ary[:, :2]) # first two columns

print(ary[:2,:]) # first two rows

1
[1 2]
1
[1 2 3]
[1 4]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]
