## npy

- 来源https://www.youtube.com/watch?v=JRXhCmmLbeY
- https://blog.csdn.net/m0_37041325/article/details/78006203
- https://blog.csdn.net/xiewenbo/article/details/73832027
- np.load和np.save是读写磁盘数组数据的两个主要函数，默认情况下，数组是以未压缩的原始二进制格式保存在扩展名为.npy的文件中
- 

In [1]:
import numpy as np

a = np.array([[1, 2, 3],
             [4, 5, 6]])

b = np.array([[6, 5, 4],
             [3, 2, 1]])

print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[6 5 4]
 [3 2 1]]


In [2]:
np.save("a.npy", a)

In [11]:
a_load = np.load("a.npy") 

print(a_load)
print(type(a_load)) ##加载之后，a_load的类型为numpy.ndarray

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


## npz 
- 是一个压缩包
- 打开之后可以看到压缩包中有两个文件，一个是x.npy,另一个是y.npz

In [4]:
np.savez("AB.npz", x=a, y=b)

In [5]:
arr = np.load("AB.npz")
print(arr) # numpy.lib.npyio.NpzFile


In [7]:
print(arr['x'])

print(arr['y'])

[[1 2 3]
 [4 5 6]]
[[6 5 4]
 [3 2 1]]


## 指定内存映射模型
- https://blog.csdn.net/qq_42825202/article/details/102620445
- 在读取文件时，我们有时候会需要读取npy文件，有时候这样一个文件特别大读取起来非常慢，甚至有可能导致电脑卡死，所以这里记下一个笔记。
- 在读取文件的时候只需要添加上读取方式，那么就会使用给定模式对文件进行内存映射，内存映射的矩阵保留在磁盘上，并不是直接全部读取到内存里。
- https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.load.html
- If not None, then memory-map the file, using the given mode (see numpy.memmap for a detailed description of the modes). A memory-mapped array is kept on disk. However, it can be accessed and sliced like any ndarray. Memory mapping is especially useful for accessing small fragments of large files without reading the entire file into memory.
- mmap_mode : {None, ‘r+’, ‘r’, ‘w+’, ‘c’}, optional

-memmap
Create a memory-map to an array stored in a file on disk.
lib.format.open_memmap
Create or load a memory-mapped .npy file.


In [ ]:
def load_data(filename,filepath):
    x=np.load(filepath+filename,mmap_mode = 'r')
    return x


In [10]:
# Mem-map the stored array, and then access the second row directly from disk:
# 内存映射保存的array，接着从磁盘直接array中的第二行
X = np.load('a.npy', mmap_mode='r')
print(X[1,:])
X[1,:]

[4 5 6]


memmap([4, 5, 6])